// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	CommonAck
	BlankMsg
	HeadBeat
	LoginReq
	LoginAck
	LogoutReq
	LogoutAck
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonAck struct {
	Status    int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	TimeStamp uint32 `protobuf:"varint,2,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CommonAck) Reset()                    { *m = CommonAck{} }
func (m *CommonAck) String() string            { return proto.CompactTextString(m) }
func (*CommonAck) ProtoMessage()               {}
func (*CommonAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommonAck) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CommonAck) GetTimeStamp() uint32 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *CommonAck) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BlankMsg struct {
	Helper bool `protobuf:"varint,1,opt,name=helper" json:"helper,omitempty"`
}

func (m *BlankMsg) Reset()                    { *m = BlankMsg{} }
func (m *BlankMsg) String() string            { return proto.CompactTextString(m) }
func (*BlankMsg) ProtoMessage()               {}
func (*BlankMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlankMsg) GetHelper() bool {
	if m != nil {
		return m.Helper
	}
	return false
}

type HeadBeat struct {
	TimeStamp int32 `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp" json:"time_stamp,omitempty"`
	Code      int32 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
}

func (m *HeadBeat) Reset()                    { *m = HeadBeat{} }
func (m *HeadBeat) String() string            { return proto.CompactTextString(m) }
func (*HeadBeat) ProtoMessage()               {}
func (*HeadBeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeadBeat) GetTimeStamp() int32 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *HeadBeat) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type LoginReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Uuid     string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	ServerId string `protobuf:"bytes,3,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LoginReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

type LoginAck struct {
	Common *CommonAck `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
}

func (m *LoginAck) Reset()                    { *m = LoginAck{} }
func (m *LoginAck) String() string            { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()               {}
func (*LoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginAck) GetCommon() *CommonAck {
	if m != nil {
		return m.Common
	}
	return nil
}

type LogoutReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LogoutReq) Reset()                    { *m = LogoutReq{} }
func (m *LogoutReq) String() string            { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()               {}
func (*LogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LogoutReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LogoutAck struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LogoutAck) Reset()                    { *m = LogoutAck{} }
func (m *LogoutAck) String() string            { return proto.CompactTextString(m) }
func (*LogoutAck) ProtoMessage()               {}
func (*LogoutAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogoutAck) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonAck)(nil), "CommonAck")
	proto.RegisterType((*BlankMsg)(nil), "BlankMsg")
	proto.RegisterType((*HeadBeat)(nil), "HeadBeat")
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*LoginAck)(nil), "LoginAck")
	proto.RegisterType((*LogoutReq)(nil), "LogoutReq")
	proto.RegisterType((*LogoutAck)(nil), "LogoutAck")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0x0b, 0x4d, 0xe3, 0xab, 0x58, 0x3c, 0x40, 0x24, 0x40, 0x42, 0x16, 0x03, 0x53, 0x06,
	0x98, 0x19, 0x28, 0x0b, 0x95, 0x60, 0x31, 0x6c, 0x0c, 0x95, 0x89, 0x4f, 0x21, 0x6a, 0x1d, 0x87,
	0xd8, 0x46, 0xe2, 0xdf, 0x63, 0x5f, 0x02, 0x65, 0xa1, 0x9b, 0xdf, 0xc7, 0xbd, 0x7b, 0x3a, 0xc3,
	0xc2, 0x7f, 0x75, 0xe8, 0xca, 0xae, 0xb7, 0xde, 0x8a, 0x57, 0x60, 0xf7, 0xd6, 0x18, 0xdb, 0xde,
	0x55, 0x1b, 0x7e, 0x0c, 0x99, 0xf3, 0xca, 0x07, 0x57, 0x4c, 0x2e, 0x26, 0x57, 0x33, 0x39, 0x22,
	0x7e, 0x06, 0xcc, 0x37, 0x06, 0x9f, 0xbd, 0x32, 0x5d, 0x31, 0x8d, 0xd2, 0x91, 0xdc, 0x11, 0xbc,
	0x80, 0xb9, 0x41, 0xe7, 0x54, 0x8d, 0xc5, 0x41, 0xd4, 0x98, 0xfc, 0x81, 0x42, 0x40, 0xbe, 0xdc,
	0xaa, 0x76, 0xf3, 0xe4, 0xea, 0x94, 0xfd, 0x8e, 0xdb, 0x0e, 0x7b, 0xca, 0xce, 0xe5, 0x88, 0xc4,
	0x2d, 0xe4, 0x0f, 0xa8, 0xf4, 0x12, 0x95, 0xe7, 0xe7, 0x00, 0x29, 0x76, 0xed, 0x68, 0xd1, 0xd0,
	0xe1, 0xcf, 0x22, 0x0e, 0x87, 0x95, 0xd5, 0x48, 0x0d, 0x66, 0x92, 0xde, 0xe2, 0x05, 0xf2, 0x47,
	0x5b, 0x37, 0xad, 0xc4, 0x0f, 0x7e, 0x02, 0xf3, 0xe0, 0xb0, 0x5f, 0x37, 0x9a, 0x66, 0x99, 0xcc,
	0x12, 0x5c, 0xe9, 0x34, 0x18, 0x42, 0x64, 0xa7, 0xc4, 0xd2, 0x9b, 0x9f, 0x02, 0x8b, 0xe2, 0xe7,
	0x60, 0x1f, 0x7a, 0xe7, 0x03, 0xb1, 0xd2, 0xa2, 0x1c, 0x53, 0xd3, 0x51, 0x04, 0x64, 0x15, 0x5d,
	0x88, 0x42, 0x17, 0xd7, 0x50, 0xfe, 0x1e, 0x4c, 0x8e, 0x8a, 0xb8, 0x04, 0x16, 0xfd, 0x36, 0xf8,
	0x7d, 0x35, 0x76, 0xae, 0x14, 0xfb, 0x9f, 0xeb, 0x2d, 0xa3, 0x8f, 0xb9, 0xf9, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x9b, 0x9d, 0x6d, 0x96, 0xa7, 0x01, 0x00, 0x00,
}
