// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	ServerCommonAck
	ServerLoginReq
	ServerLoginAck
	ServerLoginOutReq
	BrdCastGroupManageReq
	BrdCastGroupManageAck
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerCommonAck struct {
	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
}

func (m *ServerCommonAck) Reset()                    { *m = ServerCommonAck{} }
func (m *ServerCommonAck) String() string            { return proto.CompactTextString(m) }
func (*ServerCommonAck) ProtoMessage()               {}
func (*ServerCommonAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerCommonAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type ServerLoginReq struct {
	ServerId   string `protobuf:"bytes,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerName string `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
}

func (m *ServerLoginReq) Reset()                    { *m = ServerLoginReq{} }
func (m *ServerLoginReq) String() string            { return proto.CompactTextString(m) }
func (*ServerLoginReq) ProtoMessage()               {}
func (*ServerLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerLoginReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ServerLoginReq) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type ServerLoginAck struct {
	Common *ServerCommonAck `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
	Status int32            `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *ServerLoginAck) Reset()                    { *m = ServerLoginAck{} }
func (m *ServerLoginAck) String() string            { return proto.CompactTextString(m) }
func (*ServerLoginAck) ProtoMessage()               {}
func (*ServerLoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServerLoginAck) GetCommon() *ServerCommonAck {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *ServerLoginAck) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ServerLoginOutReq struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *ServerLoginOutReq) Reset()                    { *m = ServerLoginOutReq{} }
func (m *ServerLoginOutReq) String() string            { return proto.CompactTextString(m) }
func (*ServerLoginOutReq) ProtoMessage()               {}
func (*ServerLoginOutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServerLoginOutReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type BrdCastGroupManageReq struct {
	GroupId   string   `protobuf:"bytes,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberIds []string `protobuf:"bytes,2,rep,name=member_ids,json=memberIds" json:"member_ids,omitempty"`
}

func (m *BrdCastGroupManageReq) Reset()                    { *m = BrdCastGroupManageReq{} }
func (m *BrdCastGroupManageReq) String() string            { return proto.CompactTextString(m) }
func (*BrdCastGroupManageReq) ProtoMessage()               {}
func (*BrdCastGroupManageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BrdCastGroupManageReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *BrdCastGroupManageReq) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

type BrdCastGroupManageAck struct {
	Common    *ServerCommonAck `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
	GroupId   string           `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberNum int32            `protobuf:"varint,3,opt,name=member_num,json=memberNum" json:"member_num,omitempty"`
}

func (m *BrdCastGroupManageAck) Reset()                    { *m = BrdCastGroupManageAck{} }
func (m *BrdCastGroupManageAck) String() string            { return proto.CompactTextString(m) }
func (*BrdCastGroupManageAck) ProtoMessage()               {}
func (*BrdCastGroupManageAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BrdCastGroupManageAck) GetCommon() *ServerCommonAck {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *BrdCastGroupManageAck) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *BrdCastGroupManageAck) GetMemberNum() int32 {
	if m != nil {
		return m.MemberNum
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerCommonAck)(nil), "ServerCommonAck")
	proto.RegisterType((*ServerLoginReq)(nil), "ServerLoginReq")
	proto.RegisterType((*ServerLoginAck)(nil), "ServerLoginAck")
	proto.RegisterType((*ServerLoginOutReq)(nil), "ServerLoginOutReq")
	proto.RegisterType((*BrdCastGroupManageReq)(nil), "BrdCastGroupManageReq")
	proto.RegisterType((*BrdCastGroupManageAck)(nil), "BrdCastGroupManageAck")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x51, 0x5d, 0x4b, 0xf3, 0x30,
	0x18, 0xa5, 0x1b, 0xeb, 0xd6, 0xa7, 0xf0, 0xbe, 0x5a, 0x50, 0x2a, 0x22, 0x4a, 0xae, 0x06, 0xca,
	0x2e, 0xf4, 0x17, 0x68, 0x2f, 0x64, 0xa0, 0x15, 0xe3, 0x0f, 0x18, 0x59, 0x13, 0xca, 0x90, 0x24,
	0x35, 0x1f, 0x82, 0xf8, 0xe7, 0x4d, 0x9e, 0x16, 0xb6, 0x89, 0x5e, 0x78, 0x79, 0x3e, 0x7a, 0xce,
	0x73, 0x1a, 0xc8, 0xdd, 0x47, 0x27, 0xec, 0xa2, 0x33, 0xda, 0x69, 0x72, 0x05, 0xff, 0x5f, 0x84,
	0x79, 0x17, 0xa6, 0xd2, 0x52, 0x6a, 0x75, 0xdb, 0xbc, 0x16, 0x27, 0x30, 0x13, 0xc6, 0xac, 0x1a,
	0xcd, 0x45, 0x99, 0x5c, 0x24, 0xf3, 0x09, 0x9d, 0x06, 0x5c, 0x05, 0x48, 0x6a, 0xf8, 0xd7, 0xbb,
	0x1f, 0x74, 0xbb, 0x51, 0x54, 0xbc, 0x15, 0xa7, 0x90, 0x59, 0x64, 0x56, 0x1b, 0x8e, 0xee, 0x8c,
	0xce, 0x7a, 0x62, 0xc9, 0x8b, 0x73, 0xc8, 0x07, 0x51, 0x31, 0x29, 0xca, 0x11, 0xca, 0xd0, 0x53,
	0x75, 0x60, 0x08, 0xdd, 0xcb, 0x8b, 0xe5, 0x73, 0x48, 0x1b, 0xbc, 0x04, 0xc3, 0xf2, 0xeb, 0x83,
	0xc5, 0xb7, 0xf3, 0xe8, 0xa0, 0x17, 0xc7, 0x90, 0x5a, 0xc7, 0x9c, 0xb7, 0x98, 0x3b, 0xa1, 0x03,
	0x22, 0x97, 0x70, 0xb8, 0x93, 0xf9, 0xe4, 0x5d, 0x3c, 0x73, 0x6b, 0x4e, 0xf6, 0xcc, 0xcf, 0x70,
	0x74, 0x67, 0x78, 0xc5, 0xac, 0xbb, 0x37, 0xda, 0x77, 0x8f, 0x4c, 0xb1, 0x56, 0xc4, 0x0f, 0xc2,
	0x4f, 0x68, 0x23, 0xb3, 0x9d, 0x35, 0x45, 0x1c, 0x56, 0x9d, 0x01, 0x48, 0x21, 0xd7, 0x38, 0x39,
	0x96, 0x8f, 0x83, 0x98, 0xf5, 0xcc, 0x92, 0x5b, 0xf2, 0xf9, 0x53, 0xe4, 0xdf, 0xa6, 0xed, 0x96,
	0x8f, 0x7e, 0x2b, 0x57, 0x5e, 0x96, 0x63, 0x1c, 0x33, 0x94, 0xd7, 0x5e, 0xae, 0x53, 0x7c, 0xd5,
	0x9b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x5f, 0xa5, 0x2c, 0xe4, 0x01, 0x00, 0x00,
}
